[package]
name = "hd-wallet-passkey"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny-bip39 = "1.0"
bitcoin = "0.31"
secp256k1 = "0.27"
web-authn-rs = "0.3"
actix-web = "4.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
thiserror = "1.0"
async-trait = "0.1"
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio-native-tls"] }