[package]
name = "hd-wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-cors = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
web3 = "0.18"
ethereum-types = "0.14"
bip39 = "1.0"
bitcoin = "0.29"
secp256k1 = "0.24"
sha2 = "0.10"
anyhow = "1.0"
dotenv = "0.15"
env_logger = "0.9"
base64 = "0.13"
futures = "0.3"
log = "0.4"